name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Portfolio App
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{ secrets.PORT }}

          script: |
            cd ~/projects/portfolio
            git pull origin main
            npm run build
            npm install pm2
            pm2 restart portfolio
